language: node_js
node_js: node
deploy: 
  provider: heroku
  api_key:
    secure: bzipDgTjY7Fgwaqs9esaksosNtKJDh1PACOMr3IlBxWtWkoQdt1/yHcgTyXlXEJAY3u5nDOuR1n2KJg60wneEpFaQfUH3IbGpR1IIZKdrJXou0DSjh0RTkWmNX/EAp2lm/V6CnbSyFf+Zh8ngIrZRPzAnz0IxYLvCQxdtXuAMPh37dRxgWhCaRYNv+Ryd1Kkei7LD5Dpr2t0KBBT0rc9BMUxqNWqZQBXdF+jaDHBuqbwsbca1C0MnUUAYrN2Y0IrV6JLknIjTnz47itafrPAqoaAUUuI55zGwJKHDND+N3uy1oczZBpMCfwAnm2bGWHVYWxOeYCITtLyb/wGSDu9xEcuhiwjGTC3P3whPJX8H846qOTLo+jpLil9/da5kr4epiyoDVdAiISnXsBJrbfcPYmp5J7x5Kpaz3Bamv65SMQxV9nu1TISckESN430i/eOIORkQI6em4cKxllF7wyHhPs2rSLDUz8ZfSrsDLcsqKKIuY/+mW4syeaUhhWcnbIgjAX7mDV0pAfOFT5LJeZRUAb7VaLfpJHW2MB9WThk3RJQQ4bsD0FcBUDhJRIaTKz6KiHlwabta6kuSbLtGLFAIz03IqWsnrvliPBHHp7etc1yE2GX0XyE79xNTBK4C+y9U9Hh7g3rqUn/UzcMo/hjgh/b61SJ//nRAI9plSfP+mw=
  app: secret-badlands-62273
  on:
    repo: drichards211/node-shopping-list-integration-tests-v2
